### DISCUSSION TITLE
Unload All BEQ When Theater Turns Off?

### DISCUSSION THREAD

**Discussion by newoski** [iloveicedgreentea/GoWatchIt#123] [Ideas]
Would it be possible to have a setting to unload all slots and expose it to HomeAssistant? My goal is to unload all profiles when I turn the theater off or stop playback etc — useful with manually loaded BEQ files for non-Plex content

**Comment by iloveicedgreentea** [comment]
You can create a rest command in an automation to unload ezbeq via api I can send example later

**Comment by iloveicedgreentea** [comment]
I asked gemini to create the stuff try this out
```
# Part 1: REST Command Definition
# This section typically goes into your configuration.yaml file,
# or a separate file that's included in configuration.yaml (e.g., rest_commands.yaml).
# A Home Assistant restart is required after adding or changing rest_command definitions.

rest_command:
  ezbeq_delete_filter_slot:
    # The URL uses Jinja2 templates to insert the devicename and slotnumber.
    url: "http://ezbeq.local:8080/api/1/devices/{{ devicename }}/filter/{{ slotnumber }}"
    method: "DELETE"
    headers:
      accept: "application/json"
      # If your EZBEQ API requires authentication (e.g., a Bearer token), add it here:
      # Authorization: "Bearer YOUR_TOKEN_HERE"
    # Optional: Set a timeout for the request (in seconds)
    # timeout: 10
    # Optional: If ezbeq.local uses HTTPS with a self-signed certificate, you might need:
    # verify_ssl: false

# ---

# Part 2: Script Definition
# This section typically goes into your scripts.yaml file,
# or a separate file that's included in your configuration.yaml (e.g., using `script: !include scripts.yaml`).
# Scripts can usually be reloaded via Server Controls without a full HA restart.

script:
  ezbeq_delete_filters_for_device:
    alias: "EZBEQ: Delete Filters (Slots 1-4) for Device"
    description: "Deletes filters in slots 1 through 4 for a specified EZBEQ device."
    icon: mdi:delete-sweep-outline # Using a Material Design Icon

    # Define the input field for the script
    fields:
      devicename:
        name: "Device Name" # Friendly name for the UI
        description: "The name of the EZBEQ device (as it appears in EZBEQ's API/UI)."
        required: true
        example: "minidsp-flex"
        selector:
          text: # Provides a text input field in the UI when calling the script

    # Defines how the script behaves if called multiple times
    mode: single # Ensures only one instance of the script runs at a time.
                 # Use 'queued' or 'parallel' if appropriate for your use case.

    sequence:
      # Log the start of the script execution (optional, but helpful for debugging)
      - service: system_log.write
        data:
          message: "EZBEQ Delete Filters: Starting for device '{{ devicename }}'."
          level: info

      # Repeat the action 4 times (for slots 1, 2, 3, 4)
      - repeat:
          count: 4
          sequence:
            # The 'repeat.index' is 1-based, so it will provide 1, 2, 3, 4.
            - service: rest_command.ezbeq_delete_filter_slot
              data:
                devicename: "{{ devicename }}" # Pass the devicename field to the rest_command
                slotnumber: "{{ repeat.index }}" # Pass the current loop index as slotnumber
              # Optional: Log each call
              # - service: system_log.write
              #   data:
              #     message: "EZBEQ Delete Filters: Called for device '{{ devicename }}', slot {{ repeat.index }}."
              #     level: debug

            # Optional: Add a small delay between API calls if the EZBEQ server needs it.
            # - delay:
            #     seconds: 1

      # Notify that the script has completed (optional)
      - service: persistent_notification.create
        data:
          title: "EZBEQ Cleanup Complete"
          message: "Successfully attempted to delete filters in slots 1-4 for device: {{ devicename }}."
          notification_id: "ezbeq_cleanup_{{ devicename }}" # Unique ID to prevent duplicate notifications

# ---

# Part 3: Automation Definition
# This section typically goes into your automations.yaml file,
# or a separate file that's included in your configuration.yaml (e.g., using `automation: !include automations.yaml`).
# Automations can usually be reloaded via Server Controls without a full HA restart.

automation:
  - id: 'ezbeq_filter_cleanup_automation_example_v1' # A unique ID for your automation
    alias: "Example: Trigger EZBEQ Filter Deletion"
    description: "An example automation to run the EZBEQ filter deletion script."

    # Placeholder Trigger: Replace this with your actual desired trigger.
    # For example, to run when an input_boolean helper is turned on:
    trigger:
      - platform: state
        entity_id: input_boolean.run_ezbeq_cleanup_device_xyz # Create this helper in HA
        to: 'on'
    # --- Other trigger examples:
    # To run daily at 2:00 AM:
    # trigger:
    #   - platform: time
    #     at: "02:00:00"
    #
    # To run when a specific event is fired:
    # trigger:
    #   - platform: event
    #     event_type: "my_custom_ezbeq_cleanup_event"

    # Optional: Conditions to meet before the actions are run
    condition:
      # - condition: state
      #   entity_id: sensor.some_sensor # Example condition
      #   state: 'active'
      [] # No conditions by default

    action:
      - service: script.ezbeq_delete_filters_for_device
        data:
          # Specify the device name you want to target.
          # This can be hardcoded or come from a template/helper.
          devicename: "your_ezbeq_device_name_here" # <-- !!! REPLACE THIS !!!
          # Example using an input_text helper to define the device name:
          # devicename: "{{ states('input_text.ezbeq_target_device') }}"

      # If you used an input_boolean as a trigger, it's good practice to turn it off
      # after the script is called, so the automation can be triggered again.
      - if:
          - condition: template
            value_template: "{{ trigger.platform == 'state' and trigger.to_state.state == 'on' and trigger.entity_id == 'input_boolean.run_ezbeq_cleanup_device_xyz' }}"
        then:
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.run_ezbeq_cleanup_device_xyz

```

you can trigger based on playing status, button press, etc
